export const colors = {
  background: "#f5f5f0",
  backgroundMuted: "#fafaf6",
  backgroundAccent: "#eae8e3",
  backgroundCircle: "#e8e5df",
  surface: "#ffffff",
  foreground: "#1a1a1a",
  muted: "#888",
  mutedLight: "#999",
  placeholder: "#b5b5b0",
  border: "#ddd8d0",
  primary: "#2d2d2d",
  primaryDisabled: "#b5b5b0",
  error: "#b91c1c",
  errorBorder: "#e57373",
  errorBackground: "#fef2f2",
  errorBorderLight: "#fecaca",
  infoBackground: "#f0f0eb",
  infoText: "#555",
  success: "#2d8a6e",
  iconMuted: "#aaa69e",
  dot: "#d4d4d0",
} as const;
